### ISSUE TITLE
The memory usage growth was not a leak

### ISSUE THREAD

**Issue by chm** [onevcat/DispatchMemoryLeakDemo#2]
It was a side effect of a feature.

Try modifying run scheme of the target and disable a debugging option named "Queue Debugging", which would record something for each dispatched block.

Had the same confusion while this was introduced in xcode 7.0 or 7.1

**Comment by onevcat** [comment]
I tried to detach from debugger and everything goes fine. So it should be caused by the Xcode.

So it is more likely a problem in Xcode other than iOS.

I also tried to disable the queue debug option it works fine as well. Thanks for pointing it out. But I wonder why I cannot get the same memory increment in an iOS 9.1 device. If it was introduced in Xcode 7.0 or 7.1, I guess I would see the same thing in iOS 9.1?

**Comment by chm** [comment]
I'm pretty sure that when I met this issue I was using xcode 7.1 + ios 9.1, before out latest app release.
After that I've upgraded my phones to 9.2 and xcode to 7.2

As I see it this memory usage was necessary to the debuger and if it was gone on 9.1, maybe it's the debugger that went wrong.

**Comment by JohnWong** [comment]
Agree. I disconnect my iPhone and run this demo. Everything seems to be fine.

**Comment by MarcSteven** [comment]
Yeah,I also meet this issue.The version of Xcode is so unstable..disappointed...
